
default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 username: <%= ENV['FARMER_USER'] %>
 password: <%= ENV['FARMER_PASSWORD'] %>

development:
 <<: *default
 database: <%= ENV['FARMR_DEV_DB_NAME'] %>
 host: <%= ENV['FARMR_DEV_DB_HOST'] %>

test:
 <<: *default
 database: <%= ENV['FARMR_TEST_DB_NAME'] %>
 host: <%= ENV['FARMR_TEST_DB_HOST'] %>

production:
 <<: *default
 database: <%= ENV['FARMR_LIVE_DB_NAME'] %>
 host: <%= ENV['FARMR_LIVE_DB_HOST'] %>
